EnterpriseDB/barman

NEWS
Signed-off-by: Martín Marqués <martin.marques@2ndquadrant.com>
=> Typo in NEWS file refering to xlogdb

barman/server.py
Signed-off-by: Abhijit Menon-Sen <ams@2ndQuadrant.com>
=> Fix typo: consistencty → consistency

barman/cli.py
=> Allow specifying target timeline with other --target-* recovery options

barman/copy_controller.py, tests/test_copy_controller.py
Speeds up _create_dir_and_purge for empty destination directories
by ensuring exclude_and_protect_file is only populated if the
destination directory has content.
The motivation for this patch is: In cases where tablespaces
are not used the number of entries in exclude_and_protect_file
will be 2x the number of files in the PGDATA directory. As this
number enters the hundreds of thousands it can cause RSync to take
hours to execute the command created by _create_dir_and_purge
even if the destination directory is empty (as is the case when
a user is restoring to an empty directory, or barman is taking a
backup into an empty directory).
We can therefore speed up backup and restore times in these cases
by not having RSync apply the filter rules in
exclude_and_protect_file.
This is achieved by …
=> Optimize _create_dir_and_purge for empty destination

barman/cli.py, doc/barman.1.d/70-backup-id-shortcuts.md, doc/manual/43-backup-commands.en.md
=> Provide keyword to allow deletion of last failed backup

barman/diagnose.py, tests/test_diagnose.py
=> Make barman diagnose rerunnable in the same session.

tests/test_cli.py
Adds a test which verfies the help output of the ArgumentParser used by
`cli.py`. Rather than test the actual parser created by `cli.py` we
instead create a minimal parser and check its help output against an
expected output. This removes any dependency between the actual content
of the `cli.py` parser so we do not have to update this test every time
we change a command or argument in `cli.py`.
The rationale for this test is: We depend on implementation details of
argparse in order to achieve this ordering and, while argparse has
remained stable between python 2.7 and 3.10, we must assume things we
depend on will change in the future. When that happens this test will
fail and we'll be able to update barman before anything broken gets
shipped to users.
=> Add test for cli help output

doc/manual/43-backup-commands.en.md, doc/manual/50-feature-details.en.md
Fixes a number of in-document links which were broken.
=> Fix broken links in manual

barman/infofile.py
=> Sort files after walking directory

barman/clients/cloud_backup.py, barman/clients/cloud_compression.py, barman/clients/cloud_walarchive.py, barman/cloud.py, barman/cloud_providers/aws_s3.py, barman/cloud_providers/azure_blob_storage.py, doc/barman-cloud-backup.1, doc/barman-cloud-backup.1.md, doc/barman-cloud-wal-archive.1, doc/barman-cloud-wal-archive.1.md, setup.py, tests/test_barman_cloud_wal_archive.py, tests/test_cloud.py
Adds support for snappy compression to barman cloud.
Closes #344
=> Snappy Compression #344

doc/barman.5, doc/barman.5.d/50-post_wal_delete_script.md, doc/manual/99-references.en.md
Fixes a couple of errors in the docs noticed over the last few days
=> Minor docs fixes

barman/config.py, barman/output.py, tests/test_config.py
This is the branch from #526 rebased onto the latest main branch and pushed to the EDB repo so that the sonarqube and blackduck scans can run.
=> Dev/511 Handle missing config params

barman/clients/walarchive.py, tests/test_barman_wal_archive.py
This is #515 rebased to the latest main branch and pushed to the EDB repo so automated scans can run.
=> Capture and return pipe return code in barman-wal-archive

doc/manual/16-installation.en.md
=> Add SLES installation docs

tests/requirements_dev.txt, tests/requirements_minimal.txt, tests/test_utils.py
the issue came from hardcoded date timezone and now timezone not always being in the same because of summer winter shift.
=> fix broken unit test with zimezone (Closes #592)

barman/compression.py, barman/server.py, tests/test_cli.py, tests/test_compressor.py, tests/test_server.py
Fixes for #566 and #567.
See https://github.com/EnterpriseDB/barman-testing/pull/51 for integration test PR.
Closes #566.
Closes #567.
=> Custom compression fixes

doc/manual/16-installation.en.md, doc/manual/99-references.en.md
=> Update downloads links

barman/backup_executor.py, tests/test_executor.py
Uses a closing context manager when fetching the remote status during
the validation of PostgresBackupExecutor configuration. This ensures
that any server connections created during this call are not left open.
Closes #652.
=> Prevent dangling Postgres connections in BackupExecutor

doc/manual/16-installation.en.md, doc/manual/21-preliminary_steps.en.md, doc/manual/24-wal_archiving.en.md, doc/manual/41-global-commands.en.md, doc/manual/42-server-commands.en.md, doc/manual/99-references.en.md
A handful of documentation improvements as a result of #559.
=> 559 documentation improvements

barman/backup.py, barman/cli.py, barman/clients/cloud_backup.py, barman/clients/cloud_backup_delete.py, barman/clients/cloud_backup_keep.py, barman/clients/cloud_backup_list.py, barman/clients/cloud_restore.py, barman/cloud.py, barman/infofile.py, barman/output.py, barman/server.py, barman/utils.py, doc/barman-cloud-backup.1, doc/barman-cloud-backup.1.md, doc/barman.1, doc/barman.1.d/50-backup.md, doc/manual/43-backup-commands.en.md, tests/test_backup.py, tests/test_barman_cloud_backup.py, tests/test_barman_cloud_backup_delete.py, tests/test_barman_cloud_backup_keep.py, tests/test_barman_cloud_backup_list.py, tests/test_barman_cloud_restore.py, tests/test_cli.py, tests/test_cloud.py, tests/test_infofile.py, tests/test_output.py, tests/test_server.py, tests/test_utils.py, tests/testing_helpers.py
Adds support for friendly backup names in barman and barman cloud.
=> Friendly backup names

barman/backup_executor.py, tests/test_executor.py
Moves the `closing` context manager used during configuration validation so that its scope includes the validation of compression options.
This allows the connection created during the `fetch_remote_status` call to be reused when the server version is read during `_validate_compression` while also ensuring it is closed cleanly and not left dangling when the program exits.
Closes #719.
---
Notes for reviewers: Best reviewed with the [`w=1` option](https://github.com/EnterpriseDB/barman/pull/742/files?w=1).
=> Close PostgreSQL connection after compression validation

doc/manual/50-feature-details.en.md, doc/manual/99-references.en.md, doc/runbooks/snapshot_recovery_azure.md
=> Add runbook for recovering an Azure snapshot backup

barman/clients/cloud_backup_delete.py, barman/cloud.py, barman/cloud_providers/aws_s3.py, barman/cloud_providers/azure_blob_storage.py, barman/cloud_providers/google_cloud_storage.py, barman/exceptions.py, barman/xlog.py, tests/test_barman_cloud_backup_delete.py, tests/test_cloud.py, tests/test_xlog.py
Related integration tests PR can be found at EnterpriseDB/barman-testing#118
=> BAR-9: Fix wal deletion in barman cloud

doc/manual/16-installation.en.md
=> Explain difference between EPEL and non-EPEL RPMs

barman/clients/cloud_backup_delete.py, barman/retention_policies.py, doc/barman-cloud-backup-delete.1.md, tests/test_barman_cloud_backup_delete.py
Updated following initial review and rework.
We'll want to squash the commit history down before merge.
See also: https://github.com/EnterpriseDB/barman-testing/pull/124
=> Bar-10 minimum redundancy for barman cloud

barman/clients/cloud_walrestore.py, doc/barman-cloud-wal-restore.1.md, tests/test_barman_cloud_wal_restore.py
=> BAR-174: Add `--no-partial` option to `barman-cloud-wal-restore`

barman/backup.py, barman/server.py, tests/test_backup.py
When performing an incremental backup using postgres mode with the new `--incremental` flag it is required that the user has `summarize_wal` enabled on the postgres server. This PR adds a new validation method which is responsible for checking if the user has the option enabled and issue an error otherwise.
This validation could not be added to the already existing `check` method since that is also run when `barman check <server>` is issued and `--incremental` is a one-time config. I had to add a new method `validate_backup_args` to the backup manager and executors, which is called in the server context before the backup starts.
References: BAR-160
=> Check that summarize_wal is enabled on incremental backups

barman/backup.py, tests/test_backup.py
With the imminent introduction of Postgres core incremental backups support in Barman, it will become necessary to validate the possibility of taking an incremental backup.
Incremental backups establish a sequential series of backups, where the initial backup invariably constitutes a full backup. Subsequently, numerous instances may arise wherein both full and incremental backups are generated.
This PR will handle validation of the parent backup info before taking an incremental backup.
References: BAR-162
Signed-off-by: Andre [andre.marchesini@enterprisedb.com](mailto:andre.marchesini@enterprisedb.com)
=> Check that a backup is valid when taking incremental backup
