EnterpriseDB/barman

- barman/utils.py
This patch should permit barman to be called by process managers like gnu parallel who set the SIGALRM handler to ignore. SIG_IGN should be as safe as SIG_DFL in this case as the function tries to know if the signal handler has already be set.
> Don't raise error if alarm handler is ignored fix 2ndquadrant-it/barman#272

- tox.ini
Fixes the build which was failing due to flake8 not being
configured to accept the formatting applied by black.
https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html
> Update flake8 for black formatting

- barman/postgres.py
- tests/test_postgres.py
Uses the psycopg2 connection context manager so that transactions
are committed when barman uses the connection to interact with
postgres for reasons other than starting or stopping the backup.
This prevents the following situation from arising:
1. Barman starts a new transaction, for example to retrieve the
server version.
2. The transaction is left open putting the session into an
idle-in-transaction state.
3. The backup lasts longer than the value of
idle_in_transaction_session_timeout and fails because the
session is terminated.
Because this patch ensures such transactions are committed,
via the psycopg2 connection context manager, such transactions
are no longer held open during the backup.
Note that in cases where we do not call `self.connect()` directly,
a new context manager is …
> Stop backups failing due to idle transactions

- barman/clients/cloud_backup.py
- barman/clients/cloud_backup_list.py
- barman/clients/cloud_restore.py
- barman/clients/cloud_walarchive.py
- barman/clients/cloud_walrestore.py
- barman/cloud.py
- barman/cloud_providers/__init__.py
- barman/cloud_providers/aws_s3.py
- barman/cloud_providers/azure_blob_storage.py
- setup.py
- tests/test_barman_cloud_wal_archive.py
- tests/test_cloud.py
This is quite a lengthy PR so apologies in advance.
The PR makes the following changes:
1. Refactors barman-cloud so that we can more-easily add additional cloud storage backends.
2. Adds the Azure blob storage cloud provider.
3. Adds unit tests.
4. Attempts to clarify some implementation weirdness due to the differences between S3 and Azure blob storage.
The refactor commits have been split into 6 so that each stage of the process can be viewed individually - this is intended to help the reviewer and the commits can be squashed if we merge this work.
There are working integration tests in a branch of the (currently private) barman-testing repo however they can be improved so are not quite ready for PR yet.
Closes #346
> BAC-4: Add support for Azure blob storage to barman-cloud

- tests/test_cli.py
While testing #337 I was expecting the unit tests to break however this was not the case. It turns out there were a a couple of bugs in the unit tests which meant they were passing for the wrong reasons. This PR fixes those bugs and also updates the unit tests for the change merged in #337.
> Fix recovery target options tests

- barman/clients/cloud_backup.py
- barman/clients/cloud_walarchive.py
- barman/cloud.py
- barman/exceptions.py
- tests/test_barman_cloud_backup.py
- tests/test_barman_cloud_wal_archive.py
- tests/test_cloud.py
Updates barman-cloud-backup and barman-cloud-wal-archive so that they can run as post backup and post archive scripts respectively.
The implementation for barman-cloud-wal-archive is reasonably straightforward as this is a matter of reading the wal path from the environment rather than the command line.
The implementation for barman-cloud-backup is a little more involved as the original CloudBackupUploader class was written to run against a live PostgreSQL server. Rather than try and have a single backup upload method which handles both cases, the core logic for copying the backup to cloud storage is moved into a superclass and then any specific co-ordination is carried out in a different CloudBackupUploader subclass depending on whether we are running against a live PostgreSQL server or …
> Allow barman-cloud to run as hook scripts on the barman server

- tests/test_barman_cloud_backup.py
Fixes a mis-named test which was causing the build to fail at the
flake8 step.
> Fix duplicate test name

- barman/clients/cloud_backup.py
- barman/clients/cloud_backup_list.py
- barman/clients/cloud_restore.py
- barman/clients/cloud_walarchive.py
- barman/clients/cloud_walrestore.py
- barman/cloud_providers/__init__.py
- barman/cloud_providers/azure_blob_storage.py
- tests/test_cloud.py
Adds support for encryption scopes when using barman-cloud with `--cloud-provider=azure-blob-service`.
Docs to follow in a separate PR which will add all the docs for the barman-cloud Azure support.
> Support encryption scopes in Azure

- barman/cloud_providers/__init__.py
- barman/cloud_providers/aws_s3.py
Tests for the encryption parameter before passing it to
S3CloudInterface and makes it optional in the S3CloudInterface
constructor.
This is necessary because of the removal of the encryption
parameter from barman-cloud-restore, barman-cloud-wal-restore
and barman-cloud-backup-list in commit:
6f47759382063e7c452350d46f8ae4e8cf938495
> Treat encryption as optional config parameter

- barman/cloud.py
- barman/infofile.py
- tests/test_infofile.py
Adds a method named pg_major_version to BackupInfo which returns
the major version of the PostgreSQL instance from which a backup
was taken.
We deliberately avoid using a property here because we do not
want pg_major_version to be included in the backup.info fields.
It is just a convenience function.
This replaces the in-line use of `int(self.version / 10000)` in
CloudBackupUploaderBarman which only produced the correct major
version for PostgreSQL >= 10.0.
This fixes an issue where barman-cloud-backup would not copy
tablespaces when running as a hook script against backups of
PostgreSQL < 10.0..
> Fix pg major version in barman-cloud-backup hook script

- barman/cloud.py
- barman/cloud_providers/aws_s3.py
Excludes the boto3 client from the S3CloudInterface state so that
it is not pickled by multiprocessing.
This fixes barman-cloud-backup with Python >= 3.8. Previously this
would fail with the following error:
ERROR: Backup failed uploading data (Can't pickle <class 'boto3.resources.factory.s3.ServiceResource'>: attribute lookup s3.ServiceResource on boto3.resources.factory failed)
This is because boto3 cannot be pickled using the default pickle
protocol in Python >= 3.8. See the following boto3 issue:
https://github.com/boto/boto3/issues/678
The workaround of forcing pickle to use an older version of the
pickle protocol is not available because it is multiprocessing
which invokes pickle and it does not allow us to specify the
protocol version.
We therefore exclude the boto3 client from the …
> Avoid pickling boto3 client in S3CloudInterface

- barman/cloud.py
- tests/test_cloud.py
Catches exceptions encountered when reading backup.info files
during backup list operations. A warning is logged and we continue
iterating through backup files.
This fixes a problem where a single unreadable backup.info file
would break barman-cloud-backup-list entirely, preventing users
from finding any backups in cloud storage. The specific example
reported was when a backup.info file has the AWS S3 Glacier
storage class however there are other reasons why a backup.info
file might not be readable. In these scenarios we would still
want to list the backup.info files that were readable, so we
therefore catch `Exception`s rather than anything more specific.
Closes #332
> Stop backup.info errors from breaking barman-cloud-backup-list

- barman/clients/cloud_walarchive.py
- tests/test_barman_cloud_wal_archive.py
Updates barman-cloud-wal-archive in hook script mode such that it
supports running as a pre archive hook, not post archive.
This matches what we describe in the documentation and removes a
possible source of errors on restore due to compressing archived
WALs which have already been compressed by Barman. Such
double-compression is no longer possible as the pre archive script
runs before Barman has carried out any compression on the WAL.
> barman-cloud-wal-archive runs as pre archive hook

- barman/clients/cloud_walarchive.py
- barman/clients/cloud_walrestore.py
- doc/barman-cloud-wal-archive.1
- doc/barman-cloud-wal-archive.1.md
- doc/manual/55-barman-cli.en.md
- doc/manual/99-references.en.md
Adds warnings around using `--gzip` and `--bzip2` on barman-cloud-wal-archive for older python versions due to issue #325.
I stopped short of automatically refusing to run with those options on affected python versions because it's possible someone might want to archive WALs from an old machine running python 2 and restore onto a newer machine running a current python 3 - such a scenario would not be affected by issue #325 at all and would work correctly.
> Document compression issues with barman-cloud-wal-archive and older python versions

- barman/copy_controller.py
Moves the `multiprocessing.Lock` created in `barman.copy_controller`
into the class which uses it so that the lock is not created
when the module is imported and is instead created when the object
which uses it is instantiated.
This resolves an issue where barman-cloud-backup would leak one
semaphore per worker process due to the unpickling carried out as
part of `multiprocessing.spawn`. This unpickling required
importing `barman.cloud` in the worker process which, by
dependencies, would import `barman.copy_controller` and create the
lock. The associated semaphore would then be detected by the
resource tracker resulting in warnings in the logs when running
on python >= 3.8.
Closes #362
> Avoid leaking semaphores in barman-cloud-backup

- barman/wal_archiver.py
Moves the server version check for determining whether we log
pg_receivewal or pg_receivexlog so that it occurs after the initial
connection check.
This fixes the "Barman using replication slots server unreachable fails
running receive-wal" integration test which was breaking because the
call to self.server.streaming.server_version was raising an exception
directly and the expected log messages were not being logged.
> Move pg_receieve{wal,xlog} after the connection check

- barman/backup.py
- barman/clients/cloud_backup_delete.py
- barman/clients/cloud_walrestore.py
- barman/cloud.py
- barman/cloud_providers/aws_s3.py
- barman/cloud_providers/azure_blob_storage.py
- barman/retention_policies.py
- barman/server.py
- doc/Makefile
- doc/barman-cloud-backup-delete.1.md
- doc/manual/55-barman-cli.en.md
- setup.py
- tests/test_barman_cloud_backup_delete.py
- tests/test_cloud.py
- tests/test_retention_policies.py
Adds the command `barman-cloud-backup-delete` which allows backups in cloud storage to be deleted either directly via `--backup-id <BACKUP_ID>` or via a retention policy using `--retention-policy <RETENTION_POLICY>`.
The PR is structured such that the changes required elsewhere in barman and barman-cloud are made in individual commits, followed by the commit which adds the `barman-cloud-backup-delete` command.
> 368: Implement barman-cloud-backup-delete

- barman/cloud_providers/azure_blob_storage.py
- tests/test_barman_cloud_wal_archive.py
- tests/test_cloud.py
Replaces the implementation of AzureCloudInterface._check_bucket_existence
so that it does not use ContainerClient.exists. Instead we use
ContainerClient.list_blobs as a proxy for existence - if we can call
next() on the return value of list_blobs and trigger either no exception
or a StopIteration then we know the bucket exists.
This fixes the only issue which prevented the azure blob storage cloud
provider from working with SAS tokens created at the blob container
level, specifically that calling ContainerClient.exists requires storage
account permissions, not container permissions.
We also change the logic around creating the ContainerClient so that we
instantiate it directly rather than first creating a BlobServiceClient.
This isn't strictly required to fix the SAS token issue but …
> Add support for Azure SAS token at blob container level

- tests/requirements_minimal.txt
Pins the py dependency to 1.10.0 to resolve a dependabot alert.
This was previously set to <1.6.0 because 1.6.0 dropped compatibility
for python 2.6, however we no longer support python 2.6 so are free to
upgrade.
> Upgrade py dependency

- barman/backup_executor.py
- tests/test_executor.py
Check whether a `backup_info` already has `begin_time` before setting it
from a backup label in `_backup_info_from_backup_label`.
This resolves a discrepancy between the `begin_time` and `end_time`
timezones in the backup info because both `begin_time` and `end_time`
are now timestamps obtained directly from PostgreSQL and therefore have
the same timezone as the PostgreSQL server.
This only affects the `PostgresBackupStrategy` which still needs to read
the backup label when backing up a server in recovery mode as it cannot
get the WAL name and offsets directly from PostgreSQL in such cases.
The only other backup strategy which calls
`_backup_info_from_backup_label` is `ConcurrentBackupStrategy` when
backing up a <9.6 server. In these cases it uses pgespresso and
`begin_time` is not set by …
> Do not overwrite begin_time when reading backup_label

- .github/workflows/sonarqube-scan.yml
Excludes the `./build` directory from the sonarqube scan in order to stop
files within being considered as duplication of code in `./barman`.
This fixes our github actions workflow which currently fails due to
sonarqube flagging false duplicates.
> Exclude build dir from sonarqube scan

- doc/barman.conf
Make it explicit that bandwidth_limit units are kilobytes per second in
barman.conf documentation.
Closes #440
> Clarify bandwidth_limit units in barman.conf docs

- barman/cli.py
- doc/manual/15-system_requirements.en.md
- setup.cfg
- setup.py
- sphinx/requirements.txt
- tests/requirements_minimal.txt
This is an initial attempt to replace argh with the stdlib argparse library to resolve #398 
Should be compatible across all python's supported by barman (at least locally it was). The tests for the cli pass as well. However there are still some issues to resolve, like the help command showing properly the positional arguments.
Let me know what you think of that approach.
> Replace argh with argparse

- barman/copy_controller.py
- tests/test_copy_controller.py
We have a regex defined in the barman code which is in charge of
filtering out rsync error messages when rsync return code is 23.
Previous to this commit it was only covering `receiver` and `generator`
rsync processes while checking the rsync error output.
If the error was issued by the `sender` process, barman would mark
the backup as failed while checking messages like this:
```
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1178) [sender=3.1.2]
```
This very simple commit only introduces the `sender` process to the
regex pattern of `VANISHED_RE`.
More details can be also found [in the GitHub issue](#463).
> Dev/463 - VANISHED_RE now covers rsync sender process

- barman/copy_controller.py
- tests/test_copy_controller.py
Proposed fix for #465 which provides a wildcard `exclude_and_protect` file for empty directories.
Needs unit tests but wanted to get eyes on it while I continue to test it in my dev environment.
> Fix empty dir optimisation on recovery

- .github/workflows/blackduck-scan.yml
- .github/workflows/sonarqube-scan.yml
Adds a conditional to both the sonarqube-scan and blackduck-scan jobs so
that they only run if the repository is `EnterpriseDB/barman`. The jobs
will fail when running on PRs from other repositories because they do
not have access to the necessary credentials.
This prevents us from automatically failing these two checks on all PRs
from forks.
> Limit sonarqube and blackduck jobs to EDB repo only

- .github/workflows/blackduck-scan.yml
- .github/workflows/sonarqube-scan.yml
Use the github event instead of the github context to get the name of
the source repo.
> Limit sonarqube and blackduck jobs to EDB repo: Attempt 2

- barman/clients/cloud_backup.py
- barman/clients/cloud_backup_delete.py
- barman/clients/cloud_backup_keep.py
- barman/clients/cloud_backup_list.py
- barman/clients/cloud_check_wal_archive.py
- barman/clients/cloud_cli.py
- barman/clients/cloud_restore.py
- barman/clients/cloud_walarchive.py
- barman/clients/cloud_walrestore.py
- barman/cloud_providers/__init__.py
- barman/cloud_providers/azure_blob_storage.py
- doc/barman-cloud-backup-delete.1
- doc/barman-cloud-backup-delete.1.md
- doc/barman-cloud-backup-keep.1
- doc/barman-cloud-backup-keep.1.md
- doc/barman-cloud-backup-list.1
- doc/barman-cloud-backup-list.1.md
- doc/barman-cloud-backup.1
- doc/barman-cloud-backup.1.md
- doc/barman-cloud-check-wal-archive.1
- doc/barman-cloud-check-wal-archive.1.md
- doc/barman-cloud-restore.1
- doc/barman-cloud-restore.1.md
- doc/barman-cloud-wal-archive.1
- doc/barman-cloud-wal-archive.1.md
- doc/barman-cloud-wal-restore.1
- doc/barman-cloud-wal-restore.1.md
- doc/manual/55-barman-cli.en.md
- tests/test_cloud.py
- tests/testing_helpers.py
This PR improves the Barman Cloud user experience when authenticating via Azure Active Directory.
The first commit adds the functionality, the subsequent commits refactor the code in response to sonarqube warnings - I think these should be kept separate in the history so that it is clear which changes related to adding the functionality and which were due to refactoring.
Closes #396 
---
Adds the `--credential` option to the Barman Cloud scripts. The option
can be set to the following values:
* `azure-cli`: AzureCliCredential, which uses the token obtained by
logging into azure via the CLI using `az login`.
* `managed-identity`: ManagedIdentityCredential, which uses the Azure
Managed Identity endpoint to fetch a token (Barman Cloud must be
running on an Azure resource which supports …
> Add Barman Cloud option for specifying Azure credential

- barman/clients/cloud_check_wal_archive.py
- doc/barman-cloud-check-wal-archive.1
- doc/barman-cloud-check-wal-archive.1.md
- tests/test_barman_cloud_check_wal_archive.py
Updates barman-cloud-check-wal-archive such that the check passes if the
target bucket does not exist *and* we were able to successfully connect
to the cloud provider.
If we cannot successfully connect to the cloud provider then the check
errors and exits with status 2.
Closes #477.
> Pass WAL archive check if bucket is missing

- doc/manual/16-installation.en.md
- doc/manual/99-references.en.md
Will need rebasing once #475 is merged.
Not 100% happy with this as it is - maybe it's not the right place and it should be in configuration? Or perhaps we shouldn't have this information here and just add another warning in the `verify` command section (similar to what we already have with [WAL Streaming](https://docs.pgbarman.org/release/2.17/#wal-streaming) and [Streaming backup](https://docs.pgbarman.org/release/2.17/#streaming-backup).
> Update installation docs #489

- barman/clients/cloud_walarchive.py
- barman/cloud_providers/__init__.py
- barman/cloud_providers/azure_blob_storage.py
- doc/barman-cloud-wal-archive.1
- doc/barman-cloud-wal-archive.1.md
- tests/test_barman_cloud_wal_archive.py
- tests/test_cloud.py
Improves the way we use the Azure container client to upload WALs so that concurrent uploading of chunks can be used, if so desired. This can yield more than double the throughput achieved with single-request uploads.
The defaults are set in the cloud interface to the values which have experimentally yielded a measurable improvement however the defaults in the CLI arguments have been set to keep the behaviour consistent with previous versions of Barman Cloud. This is so that users can opt-in to the concurrent upload method. If things go well we can change the CLI argument defaults to match those in the cloud interface.
Closes #472
> Expose azure upload parameters #472

- barman/clients/cloud_compression.py
- setup.py
- tests/requirements_dev.txt
- tests/requirements_minimal.txt
Moves the python-snappy dependency to extras_require and lazily
imports it.
This is required so that we do not break barman on platforms which do
not have a sufficiently recent python-snappy package available in their
OS packages.
Users who wish to use --snappy compression will need to install
python-snappy with pip, the same way the cloud dependencies boto3,
azure-identity and azure-storage-blob are installed.
In the future we should look at resolving these dependencies at the OS
package level so that barman cloud does not require the manual
installation of any additional python packages.
> Make python-snappy dependency optional

- barman/clients/cloud_check_wal_archive.py
- barman/utils.py
- sphinx/conf.py
- tests/test_barman_cloud_check_wal_archive.py
- tests/test_utils.py
- tests/test_xlog.py
Closes #503
---
This is the same as #505 but pushed directly to the repo so that all the checks can run.
> Fix barman-cloud-check-wal-archive to observe -t option

- .github/workflows/black.yml
update add-and-commit action to v8
This will remove deprecation warning  "The 'pull_strategy' input is deprecated, please use 'pull'"
`pull` default behavior is no pull in v8
> Update Black pipeline

- .github/workflows/sonarqube-scan.yml
Update conditions to allow run SQ on master (Closes #518)
Could use following condition:
```
github.event_name != 'pull_request' && github.ref == 'refs/heads/master' || github.event.pull_request.head.repo.full_name == 'EnterpriseDB/barman'
```
Trigger on push is always on master so github.ref is not necessary.
So ended with something more simple that will allow push on master and manual trigger.
```
github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == 'EnterpriseDB/barman'
```
> Update conditions to allow run SQ on master (Closes #518)

- barman/cli.py
- barman/output.py
- tests/test_cli.py
Changes the implementation of show-servers so that the status
description is passed to the output writer as a separate variable
instead of appending it directly to the name of the server. This allows
the JsonOutputWriter to use just the name of the server as the key when
creating the entry in the output dict.
This fixes a bug where the key was previously the name *and* the
description, meaning the result_show_server method would then cause a
KeyError when it attempted to access the results dict by the server
name alone.
Because the JSON output is keyed by server name the description is
simply added under the description key in the output. So that this
does not get overwritten the output logic is changed so that message
values of None are skipped if there is already a value for a …
> Fix inactive server show-servers output with --format=json #488

- doc/manual/42-server-commands.en.md
- doc/manual/43-backup-commands.en.md
Updates the documentation around barman recover to describe how
--get-wal and --no-get-wal interact with recovery_options to determine
whether WALs are copied to the PostgreSQL server or fetched from the
Barman server.
Closes #521.
Thanks to @bmejiasedb for reporting this gap in the documentation.
> Improve documentation of --get-wal/--no-get-wal

- barman/server.py
- tests/test_sync.py
Adds `/data/pg_tblspc/*` to the exclude_and_protect filter during the
sync_backup operation so that any symlinks present are not transformed
into their referent directories by rsync during the sync of the backup
to a passive Barman server.
This is required in order to stop rsync from tranforming such symlinks
into their referent directories and copying them onto the passive server
along with the link targets in the root of the base backup directory.
This would result in the tablespace data being duplicated on the passive
server.
Such symlinks are only created on the primary Barman server when using
`backup_method=postgres`. When `backup_method=rsync` is used Barman
excludes the symlinks in `pg_tblspc` and therefore they are not present
when syncing to the passive server.
As a result of …
> Avoid copying contents of pg_tblspc to passive server

- doc/manual/21-preliminary_steps.en.md
Updates the documentation around the following command in the docs:
barman@backup$ psql -c 'SELECT version()' -U barman -h pg postgres
The documentation is updated so that it explains the reason for running
the command as well as stating the user and host which should be used.
Thanks to @elhananjair for reporting the issue.
> Clarify docs around verifying barman/pg connection

- setup.py
Pins protobuf to below 3.18 as python 3.5 support was formally dropped
in 3.18.
> Fix google dependencies for python 3.5

- barman/backup_executor.py
- barman/exceptions.py
- barman/postgres.py
- barman/postgres_plumbing.py
- barman/server.py
- doc/manual/21-preliminary_steps.en.md
- tests/requirements_dev.txt
- tests/requirements_minimal.txt
- tests/test_executor.py
- tests/test_postgres.py
Adds support for PostgreSQL 15.
This has been tested locally using a [barman-testing branch](https://github.com/EnterpriseDB/barman-testing/tree/add-pg15-support) and we can also use a [barman-it-set branch](https://github.com/EnterpriseDB/barman-it-set/tree/test-on-pg15) to test this in CI before merging.
Edit: Actually we need to use a [barman-packaging branch](https://github.com/EnterpriseDB/barman-packaging/tree/pg15-test) to test with since the integration tests always pull built packages and it's easier to just point the acceptance tests in barman-packaging to the updated integration tests branch.
> Add PostgreSQL 15 support

- barman/backup_executor.py
Moves the line in ConcurrentBackupStrategy.stop_backup which sets the
current_action to the very beginning of the function.
This resolves an issue where a failure retrieving the server_version
from the PostgreSQL connection would result in a misleading error
message due to the current_action still being set to
"issuing start backup command".
Closes #496
> Set current_action at start of stop_backup method

- doc/manual/16-installation.en.md
Updates the documentation around PostgreSQL binaries to account for
the fact that pg_verifybackup is provided by the server package on
RPM based distros.
Closes #547.
> Specify pg_verifybackup source on RPM systems

- doc/manual/50-feature-details.en.md
- doc/manual/99-references.en.md
Attempts to improve the documentation regarding the concurrent backup
of standby servers by:
1. Removing references to unsupported PostgreSQL versions (and
consequently PgEspresso).
2. Clarifying that backups and WALs must come from the same server but
this doesn't mean backups taken against a standby are no longer
valid once it has been promoted to primary.
3. Avoid recommending WAL streaming over archiving and instead refer
to the relevant doc sections.
4. Rewrite the warning about not streaming and archiving WALs from
a standby - this only applied to PostgreSQL 10 and earlier.
Closes #615.
> Improve docs for backing up standby servers

- barman/backup_manifest.py
- barman/cli.py
- barman/exceptions.py
- barman/fs.py
- barman/recovery_executor.py
- tests/test_backup_manifest.py
- tests/test_cli.py
- tests/test_fs.py
- tests/test_recovery_executor.py
Closes #623.
Closes #626.
See https://github.com/EnterpriseDB/barman-testing/pull/60 for related integration tests.
> Rename backup_manifest files on recovery

- barman/cli.py
- tests/test_cli.py
Allows the receive-wal options --create-slot, --drop-slot, --reset and
--stop to be used against inactive servers. If `barman receive-wal` is
called with no options in order to start WAL streaming then inactive
servers will continue to be skipped.
The rationale for this is that certain DBA procedures can require that
WAL streaming is temporarily disabled and re-enabled at a later date.
Without this patch the server must be active in order to stop WAL
streaming, reset the stream or create/drop the replication slot. While
the server is active the `barman cron` job will restart WAL streaming
if it runs. Such procedures are therefore inherently racy unless the
`barman cron` job is disabled.
By allowing the receive-wal options to run against inactive servers,
users are now able to mark the …
> Allow receive-wal options against inactive servers

- doc/barman.1.d/50-backup.md
- doc/manual/42-server-commands.en.md
The documentation of `barman backup` command both in `man` and
in the website mention that `barman backup` command can be used
to take backups from a given server or from them all sequentially
by using `all` as server name.
While taking a look at the code of barman we can see that the
server name option is filled with `nargs='+'`, which means a call
like the following:
```
barman backup server-1 server-2
```
Would sequentially backup `server-1` and `server-2`.
This commit amends the docs for `man` and for the website to
reflect that behavior.
Signed-off-by: Israel Barth <israel.barth@laptop428-ma-us.local>
> Adjusting documentation of `barman backup` command

- doc/manual/55-barman-cli.en.md
- doc/manual/99-references.en.md
Updates the barman cloud docs so that they include version requirements
for cloud provider libraries which support python2.
Closes #638.
> Document python2 cloud library versions

- barman/command_wrappers.py
- tests/test_command_wrappers.py
Adds a trailing newline to the input to stdin for the rsync
`--files-from` command.
This is a mitigation for Rsync 3.2.5 and certain versions shipped by OS
maintainers which contain a fix for CVE-2022-29154. This fix broke
`--files-from` in cases where there was no trailing newline.
Closes #659.
> Add trailing newline to rsync --files-from input

- barman/backup_executor.py
- barman/command_wrappers.py
- barman/config.py
- barman/postgres.py
- barman/server.py
- doc/barman.5
- doc/barman.5.d/50-primary_conninfo.md
- doc/manual/50-feature-details.en.md
- tests/test_command_wrappers.py
- tests/test_config.py
- tests/test_executor.py
- tests/test_postgres.py
- tests/test_server.py
- tests/testing_helpers.py
Fully implemented for both `backup_method = rsync` and `backup_method = postgres`. Unit tests included in this PR and integration tests up for review at https://github.com/EnterpriseDB/barman-testing/pull/59.
> Allow backups against `archive_mode = always` standbys to complete

- doc/barman.5
- doc/barman.5.d/50-backup_compression.md
- doc/manual/50-feature-details.en.md
Documents the requirement for the gzip, lz4 and zstd CLI programs when using `backup_compression = gzip|lz4|zstd`.
> Document dependency on gzip, lz4 and zstd CLI programs

- barman/backup_executor.py
- tests/test_executor.py
Catches connection errors when determining the server version during the validation of compression options in the PostgresBackupExecutor and logs a warning instead of letting the exception break program execution.
This is required because the BackupExecutor is on the code path for most Barman commands so if the exception is allowed to propagate then all Barman commands for a server will fail when the actual PostgreSQL server is unavailable. This is particularly absurd in the case of the `barman recover` command, when in many cases the original PostgreSQL server will indeed be unavailable.
In cases where the availability of PostgreSQL server should cause Barman to fail we rely on the existing `Server.check_postgres` function which is called during `barman check` and `barman backup`.
Closes …
> Handle PostgreSQL being unreachable during compression validation

- barman/clients/cloud_backup_delete.py
- barman/clients/cloud_cli.py
- barman/cloud.py
- barman/cloud_providers/__init__.py
- barman/cloud_providers/aws_s3.py
- barman/cloud_providers/azure_blob_storage.py
- barman/cloud_providers/google_cloud_storage.py
- barman/utils.py
- doc/barman-cloud-backup-delete.1
- doc/barman-cloud-backup-delete.1.md
- doc/barman-cloud-backup-keep.1
- doc/barman-cloud-backup-keep.1.md
- doc/barman-cloud-backup-list.1
- doc/barman-cloud-backup-list.1.md
- doc/barman-cloud-backup.1
- doc/barman-cloud-backup.1.md
- doc/barman-cloud-check-wal-archive.1
- doc/barman-cloud-check-wal-archive.1.md
- doc/barman-cloud-restore.1
- doc/barman-cloud-restore.1.md
- doc/barman-cloud-wal-archive.1
- doc/barman-cloud-wal-archive.1.md
- doc/barman-cloud-wal-restore.1
- doc/barman-cloud-wal-restore.1.md
- tests/test_barman_cloud_wal_archive.py
- tests/test_cloud.py
Provides two new features to handle requests to delete large volumes of WAL:
1. `--batch-size` parameter which determines the maximum number of objects allowed in a single delete request (#678).
2. `--read-timeout` parameter (AWS only) which allows the boto3 `read_timeout` value to be configured to something other than its default of 60 seconds (#576).
---
Related integration tests can be found at EnterpriseDB/barman-testing#76.
> Handle long running wal deletion requests

- barman/backup_executor.py
- barman/command_wrappers.py
- tests/test_command_wrappers.py
- tests/test_executor.py
Changes the log level of the default out_handler in `barman.command_wrappers.Command` from INFO to DEBUG. This means that stdout from commands invoked by Barman is now logged at DEBUG level except for pg_basebackup which is now given a custom logging handler at the INFO level.
The rationale for this change is as follows:
1. The default output handlers had been dormant for some time due to the `Command._get_output_once` function overriding any existing out_handler or err_handler with `out.append` or `err.append` respectively.
2. This meant that command output was only ever logged when the command had completed and was not logged at all while the command was in progress.
3. This issue was fixed so that the default logging out_handler and err_handler functions were used, allowing command …
> Log command output at DEBUG for all commands except pg_basebackup

- barman/postgres.py
- barman/server.py
- tests/test_postgres.py
Creates a new PostgreSQL connection to the primary in the child process which switches WALs on the primary during the call to pg_backup_stop on the standby.
This replaces the old buggy behaviour of reusing the connection from the parent process which is specifically not supported by psycopg2 or the underlying libpq library. This would lead to undefined behaviour including the closure of connections with the message `SSL error: decryption failed or bad record mac`.
We also close the connection once the child process is finished with it which avoids additional `could not receive data from client: Connection reset by peer` messages on the primary due to dangling connections.
Closes #686.
May also close #685.
> Use a new connection to primary when switching WALs

- barman/cli.py
Catches any ValueError exceptions which occur when converting the backup ID to a name and logs the result before exiting cleanly.
Previously we were just letting the exception travel to the top which meant stack traces were dumped in the logs for no good reason. This would also break the integration tests which will fail if any exceptions or tracebacks are logged during the tests.
Relates to #690.
> Catch ValueError when parsing backup ID

- .github/workflows/main.yml
The ubuntu-latest runner was recently updated to reference the ubuntu-22.04 runner. Because there are no python 2.7 or 3.6 packages available on 22.04 our unit tests cannot run against those versions using the 22.04 runner.
This isn't a bug in the 22.04 runner since these python versions are both EOL, however as long as Barman supports them we still need to run the tests on those pythons.
We therefore revert to the 20.04 runner until we either find a way to test using 2.7 and 3.6 on ubuntu-22.04 or we drop support for python 2.7 and 3.6.
> Revert to 20.04 runner for unit tests in GH workflow

- tests/test_compressor.py
Replaces `assert command.cmd.called_once()` with a call to the corresponding `assert_called_once` function. This fixes the assertion which was previously only passing due to the mock returning a truthy value.
Thanks to version 5.0.1 of the mock library for detecting this.
> Fix broken assertions in compression tests

- scripts/prepare_snapshot_recovery.py
Here is an output example:
```
/tmp/prepare_snapshot_recovery.py  -s primary -b 20221212T165659 -r recovery -n test-snapshots-gcp-recovery -p barman-324718 -z europe-west2-b
Namespace(server_name='primary')
retrieve snapshot 'primary-20221212t165659-test-snapshots-gcp-primary-pgdata' (project:barman-324718)
retrieve snapshot 'primary-20221212t165659-test-snapshots-gcp-primary-tbs1' (project:barman-324718)
Preflight checks
Validate that disk names do not already exist
Check mount points
Prepare disks for recovery
Creating disk test-snapshots-gcp-recovery-pgdata ...
Created https://www.googleapis.com/compute/v1/projects/barman-324718/zones/europe-west2-b/disks/test-snapshots-gcp-recovery-pgdata
Attaching disk 'test-snapshots-gcp-recovery-pgdata' to vm 'test-snapshots-gcp-recovery' as device …
```
> Add prepare_snapshot_recovery script(#620)

- tox.ini
These were added so that the unit tests could pass in CI however since adding them the unit tests were updated to mock out the underlying library and no longer need it.
> Remove google snapshots deps from tox.ini

- barman/backup.py
- barman/clients/cloud_backup.py
- barman/clients/walrestore.py
- barman/cloud.py
- barman/cloud_providers/__init__.py
- barman/command_wrappers.py
- barman/copy_controller.py
- barman/fs.py
- barman/infofile.py
- barman/output.py
- barman/recovery_executor.py
- barman/server.py
- barman/utils.py
- barman/wal_archiver.py
- scripts/prepare_snapshot_recovery.py
- tests/test_backup.py
- tests/test_barman_wal_archive.py
- tests/test_barman_wal_restore.py
- tests/test_cloud.py
- tests/test_compressor.py
- tests/test_output.py
- tests/test_recovery_executor.py
- tests/test_server.py
- tests/test_utils.py
- tests/testing_helpers.py
Changes the point at which the backup_name is stored in the backup_info to the creation of the backup_info rather than the `finally` block in `BackupManager.backup`. Because the backup_name will not change during the backup there is no good reason for deferring the assignment.
This fixes an issue where backup_name was not saved in the `backup.info` file when the `--wait` option was used. This was because the backup_name was assigned so late in the process that it relied on the final check of the backup to save the backup info. When `--wait` is used, this check actually happens *before* the `finally` block executes which means the backup metadata is saved before `backup_name` is assigned. This meant that the `--name` option was effectively ignored if the `--wait` option was used.
Closes …
> Store backup_name in backup_info at the earliest opportunity

- barman/postgres.py
- tests/test_postgres.py
Previous to this commit rsync-concurrent backups could fail with log messages like this:
```
2023-02-20 20:18:07,846 [31148] barman.backup_executor INFO: Asking PostgreSQL server to finalize the backup.
2023-02-20 20:18:07,846 [31148] barman.backup ERROR: Backup failed issuing stop backup command (native concurrent).
DETAILS: Connection lost, reconnection not allowed
```
That issue is triggered whenever Barman copy takes more than `idle_session_timeout` to complete because `pg_backup_start` and `pg_backup_stop` need to be executed in the same session, and the session is kept `idle` for as long as the copy takes.
This commit fixes that issue by disabling `idle_session_timeout` in the PostgreSQL session where `pg_backup_start`/`pg_backup_stop` are run.
> Disable `idle_session_timeout` for rsync-concurrent backups

- barman/backup.py
- barman/cli.py
- barman/recovery_executor.py
- barman/server.py
- doc/barman.1
- doc/barman.1.d/50-recover.md
- tests/test_recovery_executor.py
This is https://github.com/EnterpriseDB/barman/pull/707 with additional commits based on further thinking about the right way to handle the recovery options when a different destination file is requested.
---
I have squashed the original commits from #707 into a single commit ([Allow file for recovery config settings to be specified](https://github.com/EnterpriseDB/barman/pull/718/commits/ccb6b794eb1829aa10c8f3f5f8c444471990fd0d)) and also squashed the minor changes I added into [Minor changes to --recovery-conf-filename commit](https://github.com/EnterpriseDB/barman/pull/718/commits/bae473a89c273517e422725e267aa870b399120a). The rest of the commits reflect additional changes which I think can remain separate on merge/rebase.
> Configurable recovery options filename

- barman/clients/cloud_backup.py
- barman/clients/cloud_walarchive.py
- barman/cloud_providers/__init__.py
- barman/cloud_providers/aws_s3.py
- doc/barman-cloud-backup.1
- doc/barman-cloud-backup.1.md
- doc/barman-cloud-wal-archive.1
- doc/barman-cloud-wal-archive.1.md
- tests/test_barman_cloud_backup.py
- tests/test_barman_cloud_wal_archive.py
- tests/test_cloud.py
Allows the AWS KMS key ID to be specified in `barman-cloud-backup` and `barman-cloud-wal-archive` commands.
> Add support for AWS SSEKMSKeyId to barman cloud

- barman/clients/cloud_backup.py
- barman/clients/cloud_walarchive.py
- barman/cloud_providers/__init__.py
- barman/cloud_providers/google_cloud_storage.py
- doc/barman-cloud-backup.1
- doc/barman-cloud-backup.1.md
- doc/barman-cloud-wal-archive.1
- doc/barman-cloud-wal-archive.1.md
- tests/test_barman_cloud_backup.py
- tests/test_barman_cloud_wal_archive.py
- tests/test_cloud.py
Allows the kms_key_name to be specified in `barman-cloud-backup` and `barman-cloud-wal-archive`.
Based on #757
> Add support for GCP kms_key_name to barman cloud

- setup.py
Updates `setup.py` so that it specifies utf-8 encoding when opening the `version.py` file to read the version string.
This resolves a packaging error on certain Python 3.6 distributions (e.g. EL7) where the file is decoded using ascii encoding, resulting in the following error when running `python3 setup.py build`:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 26: ordinal not in range(128)
By specifying `encoding="utf-8"` we correctly decode the file and can build for Python 3.6 on EL7.
Note: This change is not compatible with Python 2.7 so should not be backported to any branch where Python 2.7 compatibility is required.
> Specify utf-8 encoding when parsing `version.py`

- doc/manual/15-system_requirements.en.md
PostgreSQL 10 will not be supported after Barman 3.5.0
> warn about pg10 drop support (closes #778)

- barman/cli.py
- tests/test_cli.py
As a passive nodes, by definition, are unable to connect to postgres in any way, we should avoid the execution of the replication-status command on them.
> Avoid the execution of replication-status command on passive nodes

- barman/backup_executor.py
- barman/cli.py
- barman/clients/cloud_backup.py
- barman/clients/cloud_restore.py
- barman/cloud.py
- barman/cloud_providers/__init__.py
- barman/cloud_providers/google_cloud_storage.py
- barman/recovery_executor.py
- tests/test_barman_cloud_backup.py
- tests/test_barman_cloud_restore.py
- tests/test_cli.py
- tests/test_cloud.py
- tests/test_cloud_snapshot_interface.py
- tests/test_executor.py
- tests/test_recovery_executor.py
Refactors parts of the implementation of snapshot backups for GCP to make it easier to add different cloud providers.
Note: The [17 Code Smells](https://sonarqube.enterprisedb.com/project/issues?id=EnterpriseDB_barman&pullRequest=793&resolved=false&types=CODE_SMELL) reported by sonarqube relate to code untouched by this commit and are present because someone tweaked the quality profiles in sonarqube. I think it's best if they are addressed in a separate PR.
> BAR-18: Make snapshots implementation more portable

- barman/clients/cloud_backup_delete.py
- tests/test_barman_cloud_backup_delete.py
Deletes the backup_label from the object store when snapshot backups are deleted. This is necessary because the existing deletion logic only deleted the `backup.info` files and the tarballs containing the backup data (which included the backup label). With snapshot backups, tarballs are not used and the backup label is stored as a unique object. It must therefore be deleted as a special case.
Closes BAR-13.
> Delete backup_label for barman cloud snapshot backups

- barman/cloud_providers/aws_s3.py
- doc/manual/28-snapshots.en.md
- tests/test_cloud_snapshot_interface.py
Adds support for deletion of AWS snapshot backups by implementing the delete_snapshot_backup function in AwsCloudSnapshotInterface.
Closes BAR-25.
> Add support for deletion of AWS snapshot backups

- doc/manual/55-barman-cli.en.md
Updates the documentation to explain the Barman backup formats for which `barmn-cloud-backup` can be used as a post backup hook script.
Closes BAR-14.
> Clarify barman-cloud-backup hook script support

- barman/cloud_providers/__init__.py
- doc/manual/28-snapshots.en.md
- tests/test_cloud_snapshot_interface.py
- tests/test_executor.py
This PR addresses issues identified by the integration tests for AWS snapshot backups.
> BAR-29: Minor AWS snapshot fixes

- doc/manual/16-installation.en.md
Adds a note to the installation section of the manual which clarifies that the Barman packages will only work with the default python3 for their target operating system.
Closes BAR-98.
> Explain python3 version requirements for packages

- barman/cloud_providers/__init__.py
Replaces the direct reference to `config.azure_credential` with one which is guarded against `config` being `None`.
Because `resource_group` was set in a similar manner the code is combined with the existing code which accessed `config.resource_group`.
Closes BAR-102.
> Fix attribute access on potential None type

- barman/clients/cloud_backup.py
- barman/postgres.py
- barman/server.py
- doc/barman-cloud-backup.1
- doc/barman-cloud-backup.1.md
- tests/test_postgres.py
Updates the help strings for the `barman-cloud-backup` compression options so that they refer to backups not WALs.
Closes #115.
> Fix help strings for barman-cloud-backup compression

- barman/command_wrappers.py
A Multiprocessing start method is the technique used by the Multiprocessing library to start child processes in Python.
There are three start methods:
* spawn: start a new Python process.
* fork: copy a Python process from an existing process.
* forkserver: new process from which future forked processes will be copied.
Each OS has a list of supported start methods:
* Windows (win32): spawn
* MacOS (darwin): spawn (default), fork, forkserver.
* Linux (unix): spawn, fork (default), forkserver.
Spawn not only is the most supported, but as per recent investigations of the devs of the Multiprocessing library, is the most secure on all the OS.
Spawn method makes use of the Pickle library for starting the new subprocesses and Pickle is unable to process internal objects and functions.
Get rid an …
> Avoid using internal functions/object with multiprocessing

- doc/Makefile
- scripts/set-version.sh
Changed set-version.sh behavior.
Instead of positional argument it uses flags.
before:
`set-version.sh 3.5.0 20231206`
now:
* `set-version.sh -r 3.5.0 -d 20231206` (identical)
* `set-version.sh -r 3.5.0 -d 20231206 -D` (using docker image)
* `set-version.sh -r 3.5.0 -D` (uses docker image and current date)
Updated release process documentation in [Source code changes](https://enterprisedb.atlassian.net/wiki/spaces/PD/pages/3407282177/release+process+with+foundation#2--Source-code-changes) section.
> allow set-version to build doc with docker image

- barman/command_wrappers.py
- barman/compression.py
- barman/config.py
- barman/recovery_executor.py
- doc/barman.5
- doc/barman.5.d/50-backup_compression.md
- doc/manual/50-feature-details.en.md
- tests/test_command_wrappers.py
- tests/test_compressor.py
- tests/test_config.py
add `backup_compression=none` to create an uncompressed archive that only supports `backup_compression_level=0`.
for pg >= 15:
update `zstd` compression level range from `-131072` to `22` update `lz4` compression level range from `0` to `12`
For PG < 15:
Allow using `backup_compression_level=0` with `backup_compression=gzip` algorithm.
In configuration 'none' can be used as value and not identified as None value.
> Update backup compression options that call `pg_basebackup`.

- tests/test_barman_wal_restore.py
Minor test correction: When running `test_ssh_port` a file  named `test_wal_dest` remains.
This will clean the test so the file is deleted when the test is done
> clean file created during test_ssh_port at the end of the test

- LICENSE
This is to fully match the GPL-3.0 wording at https://www.gnu.org/licenses/gpl-3.0.txt.
> Change http to https in LICENSE

- doc/barman.5
- doc/barman.5.d/50-archiver.md
- doc/barman.5.d/50-streaming_archiver.md
- doc/barman.d/streaming-server.conf-template
Updates the default value of the `archiver` config option in the docs with its real default and adds a note explaining:
- That it will default to `true` only if `streaming_archiver` is `off`.
- That this behaviour is deprecated and will be removed.
The docs for `streaming_archiver` are updated with a similar explanatory note.
The streaming server configuration template is also updated so that it instructs users to set `archiver = on` if archive_command is used in addition to pg_receivewal.
Closes #280.
> Clarify archiver and streaming_archiver defaults

- barman/cli.py
- barman/config.py
- barman/diagnose.py
- doc/manual/41-global-commands.en.md
- tests/test_config.py
- tests/test_diagnose.py
This PR adds a way of tracking, for each configuration option, the file that provides the effective configuration value. It is particularly useful if a user happens to define the same configuration option in more than one Barman configuration file.
In order to expose that information to the user, we added a `--show-config-source` flag to `barman diagnose` command, which when specified will change the structure of all `config` keys in the `barman diagnose` command output.
If the flag is omitted, the behavior is the same as previously: it will write a JSON object where each key is the name of the configuration option, and the value is the value of the configuration option.
On the other hand, if the flag is passed, the output format changes a bit: it will write a JSON object where each key …
> Capability of tracking the config file for each configuration option

- barman/cloud_providers/azure_blob_storage.py
Currently the azure container storage implementation of list_bucket does a depth-first traversal of the blob directory while the aws s3 implementation only lists the items in the target directory. Since doing the full traversal can be _VERY_ time-consuming when a lot of wal segments are archived in the bucket this degrades recovery operations.
We are currently experiencing 10 minute download times for a 300 byte .history file because the tree walk lists all wal segments on all timelines.
This PR removes the recursive calls and only returns first-level content similar to aws s3 implementation.
> Remove full-depth traversal - only list items in the requested 'directory'

- doc/manual/15-system_requirements.en.md
There's a requirement in the docs which is optional if you don't use rsync mode. This stated that you needed version 3.0.4 or better, yet this was not true as we need at least version 3.1.0 to use `--ignore-missing-args`.
This commit sets the documentation right so there's no confusion regarding the minimum version of rsync that is required to run barman with rsync.
> Change the minor version on the docs for rsync optionally needed

- barman/clients/cloud_walrestore.py
- tests/test_barman_cloud_wal_restore.py
The current implementation of [download_wal](https://github.com/sjuls/barman/blob/0bab1921352ea352950a062a1ab51fcb278e5250/barman/clients/cloud_walrestore.py#L121) lists all files in the wal directory and filters client-side for the actual wal being requested. However since we're querying blob storage which filters by prefix we can include the wal_name in the prefix to execute this filtering on the cloud provider while still retrieving both compressed and non-compressed files. 
The `list_bucket` api in the `cloud_interface` currently specifies prefix for filtering without any restrictions on the prefix pointing to a `folder`, and I believe all cloud providers supported by barman support filtering by any prefix as well.
This change should provide a noticeable performance improvement on wal …
> Include wal_name in list_bucket prefix to improve performance of download_wal

- barman/config.py
- tests/test_config.py
So far `barman config-update` was only able to handle server configuration.
This commit extends the command so it is now also able to handle model configuration.
Besides that we enhance the command in a couple points:
* It now logs the changes applied by `barman config-update` to the Barman configuration sections
* Some basic checks and validations are made when executing the command, e.g.:
* Basic integrity of the JSON input regarding required keys when creating or update server or model configuration
* Check if the section is what the user expects it to be, i.e., do not update a server section if the user asked to update that as a model -- and vice-versa
Unit tests updated accordingly.
References: BAR-123.
> Extend `barman config-update` to handle models

- doc/barman.1.d/50-config-update.md
- doc/barman.5.d/50-config_changes_queue.md
- doc/manual/42-server-commands.en.md
This commit introduces documentation about:
* The `barman config-update` command
* The file which is managed by Barman when calling that command (`.barman.auto.conf`)
* The `config_changes_queue` global setting, which is used by that command.
References: BAR-143.
> Include documentation about `barman config-update`

- barman/clients/cloud_restore.py
- barman/config.py
- barman/hooks.py
- barman/output.py
- doc/manual/21-preliminary_steps.en.md
- tests/test_recovery_executor.py
There was a block of SQL code added some time ago which helps users that do not want to have a superuser running the backups.
These instructions provided SQL commands to GRANT those specific privileges to the barman user.
Since version 15, two of the functions that needed to be GRANTed have not only changed their names, but also their signatures. There is a note regarding such change with appropriate instructions on the new lines to use.
Given there are already two newer versions out, and Postgres 17 coming out in a some months, it makes more sense to have instructions for the latest versions, and a note for anyone running on older Postgres versions.
This patch amends this.
> Update instructions for barman user needed privileges

- setup.py
The latest version of snappy, 0.7.1 seems to have some issues with python 3.6. Pin the version to the previous version while we investigate on the issue.
> Pin python-snappy to 0.6.1

- barman/cli.py
- doc/manual/15-system_requirements.en.md
- setup.py
Argcomplete is a nice library for bash completion but is not necessary for barman to work properly.
Installation of the lib should be optional and not enforced, and the code should handle this.
> Make argcomplete optional

- barman/cli.py
- barman/config.py
Added a guarding statement that loads the barman.auto.conf file only if the file exists.
Improved warning messages in the load_config_file method, adding a specific one in case the file is not found.
> Load the autoconf file only if it exists

- barman/config.py
- tests/test_config.py
If for whatever reason (ie: invalid JSON content or empty queue file)
The JSON parser throws an exception, emits a warning and continues with an
empty list
References: BAR-151
> Handle malformed or empty config_changes.queue file

- barman/backup_executor.py
- barman/infofile.py
- tests/test_barman_cloud_backup_show.py
- tests/test_executor.py
- tests/test_sync.py
- tests/testing_helpers.py
With postgres major version >= 17, we have the possibility to do incremental backups with pg_basebackup. 
A crucial element for enabling this functionality is the WAL summarizer process. This is a recent addition, designed to assist incremental backups by identifying the differences in the data directory since the previous backup. 
A new field was added in configuration file ` postgresql.conf` called `summarize_wal`. This field handles the state of the process (on or off).
This commit adds a new field called summarize_wal to the backup.info metadata.
For postgres versions prior to 17, this field will remain as `None`.
Unit tests updated accordingly.
References: BAR-172.
Signed-off-by: Andre Marchesini de Aguiar <andre.marchesini@enterprisedb.com>
> add summarize_wal field to backup.info (backup metadata)

- barman/backup.py
- tests/test_backup.py
Checks that the `--incremental` argument is accepted only when having `backup_method = postgres`, issue an error otherwise.
References: BAR-164
> Check postgres mode on incremental backups

- barman/backup.py
- barman/infofile.py
- barman/server.py
- barman/utils.py
- tests/test_backup.py
- tests/test_infofile.py
With the imminent introduction of Postgres core incremental backups support in Barman, it will become necessary to retrieve the latest full backup. Currently, Barman can only retrieve the most recent backup regardless of its type.
This adjustment is essential to align with the specifications outlined in the BAR-161 proposal for enhancing the command-line interface that introduces the --incremental option, which facilitates the execution of incremental backups for postgres databases.
Incremental backups establish a sequential series of backups, where the initial backup invariably constitutes a full backup. Subsequently, numerous instances may arise wherein both full and incremental backups are generated.
References: BAR-173
Signed-off-by: Andre <andre.marchesini@enterprisedb.com>
> Add shortcut to get latest full backup

- barman/infofile.py
- tests/test_infofile.py
This is much a draft.
I've added a method `walk_backups_tree` that given any backup info allows to walk the tree of children and act on them starting from leaves.
let's assume this backups structure where names of the nodes are backup_id values:
```
root_backup
/   \
child1     child2
/           \
child1.1       child2.1
/     \
child1.1.1  child1.1.2
```
the method starting from the root_backup, should walk down until the leaves and then return up.
To put it simple, assuming to execute something like this:
```python
for backup in backup_info.walk_backups_tree():
print(backup.backup_id)
```
we should get as result:
```
child1.1.1
child1.1.2
child1.1
child1
child2.1
child2
root_backup
```
This should simplify the execution of actions like backup removal, allowing to walk bottom up the …
> Backup tree walking using yield

- barman/recovery_executor.py
- tests/test_recovery_executor.py
Previous to this commit there could be cases where Postgres would be misconfigured by `barman recover`.
For example, assume you had an environment like this:
* Barman host configured with time zone UTC+2, e.g. `Europe/Berlin`;`
* Postgres cluster with default value for timezone GUC, i.e. GMT value.
If we attempted a `barman recover` execution with `--target-time` set, but without an explicit time zone, recovery could fail:
* `barman recover` output would say that recovery target time was set with `+02:00`;
* However `postgresql.auto.conf` would not contain `+02:00`.
In practice either the recovery would fail because of an invalid recovery target, or the cluster would be recovered to a point-in-time different from the user needs. Neither of these cases are welcome.
This commit fixes that …
> Always add an explicit time zone to `recovery_target_time`

- barman/cli.py
- tests/test_cli.py
An incremental backup with the keep annotation that has its parent deleted would become an orphan backup and therefore useless for recovery. To avoid this, we should restrict the use of keep annotations to full backups only. This adds a new check prior to starting the annotation process to make sure we do not allow keeping a backup if it has a parent backup, raising an error if so.
References: BAR-184
> Restrict the use of keep annotations to full backups only

- barman/recovery_executor.py
- barman/server.py
- tests/test_recovery_executor.py
- tests/test_server.py
Previous to this commit Barman would attempt to guess the required WAL files using the filesystem creation timestamp of them.
However, that is not a reliable approach. For example, if there is streaming replication lag, the WAL files will be created in the Barman host later when compared to Postgres.
That can be even worse in the case of `archive_command`, because it waits for the WAL files to be filled up before making them available for archiving.
In those cases the recovery could end up failing because of missing `COMMIT` or `ABORT` records in the WAL files that were copied by Barman, i.e. Postgres would fail to perform recovery because it wouldn't know if it satistified or not the requested `recovery_target_time`.
From now on, if the user requests a recovery with `--no-get-wal` and …
> When recovering with `--no-get-wal` and `--target-time`, copy all WAL files

- barman/recovery_executor.py
- barman/server.py
- tests/test_server.py
Previous to this PR, when the user specified `--target-lsn` and `--no-get-wal` in `barman recover` command, Barman was copying all WAL files from Barman to Postgres.
As we are able to infere the required WAL files based on the specified `--target-lsn`, this PR changes Barman so it copies only the required WAL files instead of them all.
Notes:
* We also added a missing unit test to cover the case where `--target-xid` is specified;
* This PR is based on #951. That PR needs to be merged before this PR.
References: BAR-190.
> When recovering with `--no-get-wal` and `--target-lsn`, bring only the WALs up to the specified LSN

- barman/backup.py
- barman/server.py
- tests/test_backup.py
- tests/test_server.py
This PR got bigger than I expected so I will try to explain the changes per commit.
In 129c6723302daea0f7a59954fd303b53f578b36c is the implementation for deleting descendant backup nodes when a parent is deleted. To achieve this, I divided the current `delete` method of the `Server` into two methods:
- `delete` which will now have some validations to make sure the backup is deletable (this used to be done later in the backup manager) as well as pass the whole chain for deletion inside a server level lock;
- `perform_delete` will be doing some of the same work that the previous delete method was doing i.e. validating file permissions, holding the backup level lock and calling the `BackupManager.delete`. One thing to notice here is that this code used to acquire a server lock in the …
> Implementation of backup tree deletion

- barman/infofile.py
- barman/retention_policies.py
- tests/test_barman_cloud_backup_delete.py
- tests/test_infofile.py
- tests/test_retention_policies.py
Starting from Postgres version 17, the introduction of incremental backups ensures a continuous chain of backups beginning with a full backup and extending through several incremental backups, specifically when backup_method="postgres". Consequently, any retention policy should exclusively target full backups for
deletion, as incremental backups rely on their parent chain of backups to remain valid and usable.
This commit:
1. Add new method to RetentionPolicy class
1.1 propagate_retention_status_to_children
- This new method is used to set the retention status for incremental backups. This is needed because we want to control the retention status of the incremental backup based on its parent backup (AKA full backup). This will propagate the parent retention status to its children …
> Modify retention policies so incremental backups are ignored

- setup.py
The library `python-snappy` internally uses the library cramjam from versions > 0.6.1.
This doesn't work well with versions of cramjam < 2.7.0 as the structure of the code is different than the one used by python-snappy.
References: bar-156
> Require cramjam lib to be >= 2.7.0

- barman/clients/walrestore.py
This should speed up serving wal-files from the spool-directory, in case `pg_wal` and the spool-directory are on the same filesystem, as in this case the file is renamed instead of copied.  
If those directories are on different file-systems, this doesn't change anything, as `shutil.move` will do the same 2-step-process (copy and remove) in that case. [Docs for reference](https://docs.python.org/3/library/shutil.html#shutil.move).
Also see ticket #943
> uses shutil.move instead of copy and unlink

- barman/cli.py
- barman/clients/walrestore.py
- barman/command_wrappers.py
- barman/infofile.py
- barman/recovery_executor.py
- tests/test_cli.py
- tests/test_command_wrappers.py
- tests/test_infofile.py
- tests/test_recovery_executor.py
pg_combinebackup utility is coming to Postgresql 17 with the introduction of incremental backup to reconstruct a synthetic full backup from a sequence of incremental backups and the previous full backup.  
This PR:
- Create a new command wrapper for the `pg_combinebackup` utility.
- Create a new recovery executor, which does the following:
1. Get the backup chain and combine them into a synthetic backup in a common staging path
2. Reuse the recover method from the `RecoveryExecutor` super class, by passing the newly created synthetic backup;
3. In the copy phase, we check if is remote or local recovery:
a. if it is remote, we reuse the rsync logic already present in the parent recovery executor;
b. if it is local, we move the data directory and tablespaces from staging to the destination. …
> create new recovery executor that uses `pg_combinebackup`

- barman/backup_executor.py
- barman/infofile.py
- tests/test_barman_cloud_backup_show.py
- tests/test_executor.py
- tests/test_postgres.py
- tests/test_sync.py
- tests/testing_helpers.py
After the introduction of incremental backups in Postgres 17, there is the need to review how we display information about backups, specially when using the `show-backup` command. Because of this need, we are adding the `cluster size` field to the backup.info. 
This new field is intended to be used in the calculation of the deduplication_ratio of backups and to show the estimated size of the Postgres cluster at the time the backup was taken. For this, we are reusing an existing property of the `PostgreSQLConnection` class called `current_size`.
The tests broken by the changes on the code were fixed.
Unit tests for the `current_size` property were added because they were found to missing from the test suite and the unit test for the `_pg_get_metadata` method of the `BackupStrategy` class …
> Get database cluster size and add to `backup.info`

- barman/output.py
- tests/test_output.py
Displaying tablespace information for each backup often leads to unclean outputs in `list-backups`. Now, tablespace and other verbose information about each backup will only be shown by the `show-backups` command, while `list-backups` gets more concise.
References: BAR-216
> Remove tablespace information from the `list-backup` output

- barman/infofile.py
While working on the new list-backup (BAR-207), a bug was spotted in the method `is_full_and_eligible_for_incremental` from the `LocalBackupInfo` class.
The method was using the volatile information `backup_method` of the server configuration. This would be harmful if the user creates backups with backup_method='postgres' and changes to 'rsync'. When using list-backup or show-backup commands, the user would get an error. To fix this, we just need to use the `mode` field from the `backup.info` object, which is what this commit is doing.
References: BAR-228
> Fix bug in `is_full_and_eligigle_for_incremental` method

- barman/backup.py
- tests/test_server.py
The `check-backup` command can mark a backup as failed if it notices that some of its required WAL files are missing. This works correctly, however no output is provided, so the only way to check why the backup has been marked as failed is by executing a `show-backup` on the backup. This commit fixes this issue by outputting the reason as an error message in the CLI.
Note: I though about using debug or warning log level, but considering that, as I've seen, there's a change of this happening also during a backup, I think it's better to display it with an error level instead. Also, if by any chance the user runs this manually they should be able to see the failure reason immediately on the screen I think.
References: BAR-213
> Output info from the check-backup command

- barman/backup_executor.py
- barman/infofile.py
- barman/output.py
- barman/recovery_executor.py
- barman/server.py
- tests/test_barman_cloud_backup_show.py
- tests/test_executor.py
- tests/test_infofile.py
- tests/test_output.py
- tests/test_sync.py
- tests/testing_helpers.py
Postgres incremental backups have the risk of the user switching the `data_checkums` configuration on the server between backups, which could potentially cause problems during recovery. An attempt of reducing these cases is implemented in this PR, where we will now store the state of `data_checksums` in the `backup.info` file of each backup, which will allow Barman to check the consistency of the chain during backup and recovery execution and emit warnings to the user so they can take action about it.
- 67b16d71e2f5a3bea23b18348031c46b56d5f406 Add the new `data_checksums` config to the `backup.info` file
- eb68c24f4da496686aa1d8788f17e76f012ea40c Fix tests broken due to the new config added in the previous commit
- b116e52d4e363ae01d58f9f959763dda876ccc1e Add a new method …
> Checks checksum consistency on backup chain

- barman/infofile.py
- barman/output.py
- tests/test_infofile.py
- tests/test_output.py
Add a new label to each backup in the `list-backup` output that references the backup type considering:
- R: for rsync backup
- F: for full pg_basebackup
- I: for incremental pg_basebackup
If a backup doesn't have a parent backup nor the backup method set to rsync, it's labeled as a full backup. This also adds a new field "backup_type" to the JSON output, containing the type label.
To get the correct backup type without relying on volatile information, a new property `backup_type` was added to the `LocalBackupInfo` object, which returns the label for `backup.info` at backup time instead of relying on the configuration at runtime. 
References: BAR-207
> Add full and incremental backup information to `list-backup`

- barman/recovery_executor.py
- barman/server.py
- tests/test_server.py
This PR is resolving an issue reported in GH issues #205.
Previous to this PR, when the user specified `--target-immediate` to `barman recover`, and the recovery process was configured with "no get wal" method, Barman was copying all WAL files available in the Barman archive to the recovery destination.
With the changes introduced by this PR, when `--target-immediate` flag is specified to `barman recover`, Barman copies only the WAL files required for the recovery process to reach the consistent point instead of copying all the available WALs.
References: BAR-223
Closes: #205
> Fix --target-immediate option copies all WAL files

- barman/server.py
Fixes #539 where some errors of the `receive-wal` command were exiting with a status of zero, indicating success. The referenced issue reports an error when using the `--reset` option, but the same also occurs with another error when you execute it without the flag and a receive-wal process is already running. This commit fixes both.
In the code, it was just a matter of using the proper logging type and the rest is already handled. Now both errors exit with a status different than zero:
```
[gustavo@localhost ~]$ barman receive-wal --reset pg17_server
ERROR: Unable to reset the status of receive-wal for server pg17_server. Process is still running
[gustavo@localhost ~]$ echo $?
1
```
```
[gustavo@localhost ~]$ barman receive-wal pg17_server
Starting receive-wal for server pg17_server …
```
> Fix receive-wal command exiting with status 0 on errors

- barman/backup.py
- tests/test_backup.py
- tests/testing_helpers.py
Backups taken with pg_basebackup can get compression. On the other hand, incremental backups with barman cannot leverage that feature yet because `barman recover` is not prepared to combine compressed backups, so barman needs to prevent users from taking backups with the `backup_compression` option set in the configuration file. For the same reason, Barman also needs to prevent users from taking incremental backups on top of backups that were compressed when taken.
This PR is adding those checks to be made before taking any incremental backup and the unit tests for both use cases.
References: BAR-253
> Add check of backup compression when taking incremental backups

- barman/fs.py
- tests/test_fs.py
Opening a new PR as I got the wrong branch naming in #978
What this PR is doing:
c05da293ca531248d4f8a7ba47dbf81d78459592 fixes an issue with the barman diagnose command, where it was actually getting the Python version from the first Python interpreter found in the PATH environment variable instead of the one the Barman is actually using to run. This could lead to wrong outputs if the one found in PATH is different from the one that Barman is using. This was fixed by getting the version from the sys module instead of the python --version command which was previously.
c935a76ce380f19f4ca831caa24d0281bae6d17a adds also the Python executable path to the Barman diagnose output, as suggested by @gcalacoci
ba6956f1c99076d4a7557c666ba5285dde4c90b9 adds tests to the `get_system_info` method of …
> fixes and improvements on  `barman diagnose` command

- barman/backup.py
- tests/test_backup.py
When deleting a backup, if the next backup is rsync it might contain outdated disk usage and deduplication information, which should therefore be re-calculated after the deletion. This occurs because rsync backups have deduplication at the filesystem level when using the "reuse_backup = link" option, and since the deduplication size is calculated at the time the backup is taken, deleting an rsync backup might cause the deduplication information of the subsequent backup to become inaccurate.
With the implemented changes, whenever a backup is deleted from the catalog, if there is a next rsync backup in the server, its disk information will be updated using the new method  `_set_backup_sizes`. This method updates backup information and can optionally also fsync to disk, so …
> Fix "backup size" of rsync incremental backups upon deletion of backups

- barman/infofile.py
- tests/test_infofile.py
- tests/test_output.py
Update `backup_type` property to also return the label for snapshot backups and adjust the unit tests accordingly. Since the updates to the `list-backup` command introduced by BAR-207 on adding backup type information to the output did not account for snapshot backups, this update fixes this oversight.
References: BAR-268
> Add "snapshot" backup type to `list-backup` output

- doc/barman.1.d/50-list-backups.md
- doc/manual/42-server-commands.en.md
Update the docs according to the new output of the `list-backups` command, which now also displays the backup type, and complement information on how to generate the output in JSON format.
References: BAR-254
> Update docs according to changes to the `list-backup` command

- doc/barman.1.d/50-backup.md
- doc/barman.5.d/50-keepalive-interval.md
- doc/manual/26-rsync_backup.en.md
Add in the docs a description of the new `keepalive_interval` server configuration as well as your equivalent CLI argument `--keepalive-interval` that can be specifided together with the `backup` command.
References: BAR-256
> Add docs about the new keep-alive mechanism

- doc/manual/43-backup-commands.en.md
The use of keep annotations should be restricted to full backups only as it could lead to having orphan backups in a case where a Postgres incremental backup has its parent deleted while having the keep annotation. Such an incremental backup will then be useless for recovery.
This PR is adding a note to the documentation of the barman `keep` command
References: BAR-258
> Add doc about keep restriction on incremental backups

- doc/barman.1.d/50-recover.md
- doc/barman.5.d/50-local_staging_path.md
- doc/manual/43-backup-commands.en.md
There are changes in the behavior of barman recover with the new incremental backup feature. This PR will add the proper documentation about the recover of incremental backups.
This needs to address:
1.   Add note with a brief description of how Barman recovers the backups, mainly mentioning the use of pg_combinebackup, etc.
2.  Mention the use of the `local_staging_path` to place the `pg_combinebackup` synthetic backup.
3.  Add note, with links to the PG docs about checksums being on and off in different backups of a chain of backups.
4. Add field and details about `local_staging_path` to args in the man1 recover command documentation.
References: BAR-252
> Add doc about incremental backup recover in the manual

- doc/manual/43-backup-commands.en.md
Adds some explanation in the docs about how dependent Postgres incremental backups are going to be deleted along with their parent as they become useless for recovery in such cases.
References: BAR-251
> Add docs for the deletion of incremental backups

- barman/backup_executor.py
We have found that in certain corner cases the exceptions happening during rsync backups execution could be not correctly logged and even be hidden by subsequent exceptions happening in the `finally` statement that takes care of finalizing the backup.
To avoid that, we added a `logger.debug` line that always prints in debug mode the stack trace of exception happening during the execution of rsync backups.
References: BAR-277
> Improve barman logging capabilities

- doc/manual/43-backup-commands.en.md
Adds a note in the docs about the behavior of `--target-time` when no timezone is specified, in which case the Barman host timezone is used instead.
References: BAR-257
> Add docs about the behavior of --target-time with no timezone

- doc/manual/50-feature-details.en.md
After the introduction of incremental backups in PostgreSQL 17, we need to document the behavior of the retention policies for incremental backups.
This commit is adding the explanation to the `Retention Policies` section of the Barman Manual.
References: BAR-250
> Add doc about retention policy of incremental backup

- barman/cli.py
- barman/infofile.py
- barman/recovery_executor.py
- tests/test_cli.py
- tests/test_infofile.py
- tests/test_recovery_executor.py
In the beginning of the implementation of the incremental backups when released with PostgreSQL 17, we introduced a `parent_backup_id` field to the BackupInfo class, and we had been using that to distinguish between incremental and non-incremental backups.
At some point we introduced a new property `is_incremental` which abstracts that logic. However, that property started being used in new code after that, but was not used in the places where there were already checks on `parent_backup_id`.
This PR is taking care of that and replacing all checks made with `parent_backup_id` for the property `is_incremental`. 
Also the unit tests were all modified according to the changes in implementation.
References: BAR-276
> Replace checks on `parent_backup_id` with the property `is_incremental`

- doc/barman.1.d/50-show-backup.md
- doc/manual/50-feature-details.en.md
After the introduction of incremental backups in PostgreSQL 17, new fields were added to the backup info and a new output of the show-backup command was implemented.
This PR is modifying the documentation so users can have a better sense of the show-backup output.
Summary of changes:
1. A small change was made in the "Backup metadata for snapshot backups" part in the manual.
2. A bigger change was made in the man1 where the `show-backup` command is explained and detailed.
References: BAR-275
> Change docs related to `show-backup` command new output

- doc/manual/43-backup-commands.en.md
When recovering with --no-get-wal and with either of --target-xid, --target-name or --target-time (the latter being a change introduced by Barman 3.11), Barman will copy the whole WAL archive from the Barman host to the recovery host.
That’s done that way because there currently is no reliable/performant way of “guessing” before-hand the required WAL files to reach the configured recovery target.
This commit is adding an important note to the manual doc explaining that limitation.
References: BAR-278
> Explain limitations of `--target-{xid | time | name}` when using `--no-get-wal`

- doc/barman.1.d/50-backup.md
- doc/barman.1.d/70-backup-id-shortcuts.md
- doc/manual/10-design.en.md
- doc/manual/25-streaming_backup.en.md
- doc/manual/26-rsync_backup.en.md
- doc/manual/42-server-commands.en.md
- doc/manual/50-feature-details.en.md
Change docs to explain the new `--incremental` option that can be used together with the `backup` command. Some sections which mentioned incremental backups are being something specific to Rsync were also changed to take the new block-level incremental option into account.
References: BAR-249
> Change docs to introduce the new --incremental option

- barman/output.py
- doc/barman.1.d/50-show-backup.md
- tests/test_output.py
Resources saved is a better and clearer name
> Rename `Resource savings` into `Resources saved`

- doc/manual/43-backup-commands.en.md
- doc/manual/50-feature-details.en.md
Change mentions of "incremental backup" in the docs to explicitly tell which type of backup it's talking about i.e. block-level or file-level.
References: BAR-283
> Change docs to clarify which type of backup it's talking about

- doc/manual/50-feature-details.en.md
Adds a note to both file-level and block-level incremental backup sections to highlight that they're currently incompatible with each other.
References: BAR-281
> Add note in docs about incompatibility of backup types

- barman/infofile.py
- tests/test_infofile.py
Through Barman 3.11.0 we introduced native PG17+ incremental backups. Some changes have been made to the backup metadata to support that.
As part of the changes, we introduced a few properties to the class `LocalBackupInfo`. However, there was an oversight in some code paths which are shared between local and cloud backups.
For example, when running `barman-cloud-backup-delete`, that command reuses the retention policy classes. These, in their turn, attempt to access the aforementioned properties.
This commit fixes the issue by moving the new properties to the base `BackupInfo` class, so they are available both for local and for cloud backups.
The properties `has_children` and `is_incremental` will always return `False` for cloud backups. Analagously, `deduplication_ratio` and …
> Fix failures in `barman-cloud-backup-delete` related with incrementals

- doc/manual/43-backup-commands.en.md
This commit Closes: #200 .
It adds a note to the recovery section of the documentation manual. This note informs users about the risk of backup obsolescence and deletion during the recovery process, particularly when retention policy rules are enforced, and provides guidance on how to prevent this issue.
Initially, the team considered implementing an automatic solution for this problem. However, several concerns were raised, including the potential for unintended side effects during recovery, the existing `keep` feature designed to assist with backups, and the need for users to be fully aware of the implications and procedures during recovery—an operation often conducted under stressful situations.
References: BAR-222
> Add note in the manual about recovery near retention policy

- .github/workflows/linter.yml
- .gitleaks.toml
- .hadolint.yaml
- .isort.cfg
- .markdownlint.yml
- .python-black
- .yamllint.yml
This PR is
* Adding the `linter.yml` workflow to the barman repository
* Adding the files that are referenced in the workflow
* .gitleaks.toml
* .hadolint.yaml
* .isort.cfg
* .markdownlint.yml
* .python-black
* .yamllint.yml
References: BAR-361
> Add super linter to Barman

- barman/postgres.py
- tests/test_postgres.py
To work correctly Barman database user should be included in some roles ad this is checked by `pg_has_role` function.
In all `pg_has_role` functions `MEMBER` privilege is checked but in Barman code no `SET ROLE` is present so it better to check in `pg_has_role` functions `USAGE` privilege instead (that includes `INHERIT` check).
`pg_has_role` function documentation: https://www.postgresql.org/docs/16/functions-info.html#id-1.5.8.32.4.4.2.2.14.1.1.1
PR already discussed with @martinmarques here: https://github.com/EnterpriseDB/repmgr/pull/807#discussion_r1750197750
> Check for USAGE (instead of MEMBER) privilege in all pg_has_role occurrences
